name: 'Automated Tests'
on:
  pull_request:
    branches: [main]
jobs:
  test:
    name: 'Jest Tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Set up Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/krypton'
      - name: 'Install Dependencies'
        run: npm ci
      - name: 'Run Tests'
        run: npm test
